### ISSUE TITLE
Can't save created profiles

### ISSUE THREAD

**Issue by Comodooo** [wagiro/BurpBounty#40]
Awesome extension, but I'm having some trouble trying to save profiles that I have created. Nothing is showing up sadly after I try to add tags. I'm using v2.1.03 on Burp.

**Comment by wagiro** [comment]
Hi Comodooo!

You should specify the profiles directory first, have you specified?

Regards.

**Comment by Comodooo** [comment]
Hi Wagiro,

Yeah I specified a profile directory, problem now is that the extension itself wont even load...

Tried to remove it and download your latest build again and import it, but it dosen't show up or give me any error messages with it.

**Comment by Comodooo** [comment]
I can unload all other extensions and they pop back up, but not the bounty one.

**Comment by Comodooo** [comment]
Also tried going for the "Scan check builder" but it's the same story there. Any tips?

**Comment by wagiro** [comment]
Can you execute burpsuite through console with java -jar burpsuite.jar, for see any errors??

**Comment by Comodooo** [comment]
`class java.lang.IllegalStateException
java.lang.IllegalStateException: This is not a JSON Array.
        at com.google.gson.JsonElement.getAsJsonArray(JsonElement.java:106)
        at burpbounty.BurpBountyGui.makeTagsFile(BurpBountyGui.java:1635)
        at burpbounty.BurpBountyGui.<init>(BurpBountyGui.java:194)
        at burpbounty.BurpBountyExtension.lambda$registerExtenderCallbacks$0(BurpBountyExtension.java:76)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
class java.lang.IllegalStateException
java.lang.IllegalStateException: Not a JSON Array: "<!DOCTYPE"
        at com.google.gson.JsonElement.getAsJsonArray(JsonElement.java:107)
        at burpbounty.BurpBountyGui.makeTagsFile(BurpBountyGui.java:1639)
        at burpbounty.BurpBountyGui.<init>(BurpBountyGui.java:198)
        at burpbounty.BurpBountyExtension.lambda$registerExtenderCallbacks$0(BurpBountyExtension.java:76)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)`

**Comment by Comodooo** [comment]
Seems like a wonderful classic java error message :)

**Comment by Comodooo** [comment]
Ok, I uninstalled burp and now I was able to load the extension, but still not able to load the profiles from the folder that I specified.

**Comment by wagiro** [comment]
Mmmm seems like on of your profiles .bb are corrupted, try a empty folder or my github folder

**Comment by Comodooo** [comment]
@wagiro so sorry for the spamming.... I tried loading one of your profiles but I't didn't really want to do that.... But for some reason I was able to create my own tag and profile now, so I'm guessing we can close this now. Sorry again for the spamming.

**Comment by wagiro** [comment]
No problem man :)
