### ISSUE TITLE
BurpBountyExtension: Index 1 out of bounds for length 1

### ISSUE THREAD

**Issue by s1xg0d** [wagiro/BurpBounty#62]
BurpSuite version:v2020.5
BurpBounty version: v3.3
Site: testphp.vulnweb.com 
![image](https://user-images.githubusercontent.com/8321329/84226691-0f71ca80-ab15-11ea-8924-22421970b7b0.png)

Not vulns found.  😢

**Comment by wagiro** [comment]
Hi @s1xg0d !

Can you show me the error from the beginning?

Thanks!

**Comment by s1xg0d** [comment]
> Hi @s1xg0d !
> 
> Can you show me the error from the beginning?
> 
> Thanks!


```
	at burpbounty.GenericScan.runAScan(GenericScan.java:217)
	at burpbounty.BurpBountyExtension.doActiveScan(BurpBountyExtension.java:180)
	at burp.du4.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
java.lang.RuntimeException: Extension generated task deleted
	at burp.w6.makeHttpRequest(Unknown Source)
	at burpbounty.GenericScan.runAScan(GenericScan.java:217)
	at burpbounty.BurpBountyExtension.doActiveScan(BurpBountyExtension.java:180)
	at burp.du4.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
java.lang.RuntimeException: Extension generated task deleted
	at burp.w6.makeHttpRequest(Unknown Source)
	at burpbounty.GenericScan.runAScan(GenericScan.java:426)
	at burpbounty.BurpBountyExtension.doActiveScan(BurpBountyExtension.java:180)
	at burp.du4.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
BurpBountyExtension line 174: Extension generated task deleted
java.lang.RuntimeException: Extension generated task deleted
	at burp.w6.makeHttpRequest(Unknown Source)
	at burpbounty.GenericScan.runAScan(GenericScan.java:426)
	at burpbounty.BurpBountyExtension.doActiveScan(BurpBountyExtension.java:180)
	at burp.du4.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
BurpBountyExtension line 174: Extension generated task deleted
java.lang.RuntimeException: Extension generated task deleted
	at burp.w6.makeHttpRequest(Unknown Source)
	at burpbounty.GenericScan.runAScan(GenericScan.java:426)
	at burpbounty.BurpBountyExtension.doActiveScan(BurpBountyExtension.java:180)
	at burp.du4.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
BurpBountyExtension line 174: Extension generated task deleted
BurpBountyExtension line 174: Index 1 out of bounds for length 1
BurpBountyExtension line 174: Index 1 out of bounds for length 1
BurpBountyExtension line 174: Index 1 out of bounds for length 1
BurpBountyExtension line 174: Index 1 out of bounds for length 1
BurpBountyExtension line 174: Index 1 out of bounds for length 1
BurpBountyExtension line 174: Index 1 out of bounds for length 1
BurpBountyExtension line 174: Index 1 out of bounds for length 1
BurpBountyExtension line 174: Index 1 out of bounds for length 1
BurpBountyExtension line 174: Index 1 out of bounds for length 1
BurpBountyExtension line 174: Index 1 out of bounds for length 1
BurpBountyExtension line 174: Index 1 out of bounds for length 1
BurpBountyExtension line 174: Index 1 out of bounds for length 1
BurpBountyExtension line 174: Index 1 out of bounds for length 1
BurpBountyExtension line 174: Index 1 out of bounds for length 1
BurpBountyExtension line 174: Index 1 out of bounds for length 1
BurpBountyExtension line 174: Index 1 out of bounds for length 1
BurpBountyExtension line 174: Index 1 out of bounds for length 1
BurpBountyExtension line 174: Index 1 out of bounds for length 1
BurpBountyExtension line 174: Index 1 out of bounds for length 1
BurpBountyExtension line 174: Index 1 out of bounds for length 1
BurpBountyExtension line 174: Index 1 out of bounds for length 1
BurpBountyExtension line 174: Index 1 out of bounds for length 1
BurpBountyExtension line 174: Index 1 out of bounds for length 1
BurpBountyExtension line 174: Index 1 out of bounds for length 1
BurpBountyExtension line 174: Index 1 out of bounds for length 1
BurpBountyExtension line 174: Index 1 out of bounds for length 1
BurpBountyExtension line 174: Index 1 out of bounds for length 1
BurpBountyExtension line 174: Index 1 out of bounds for length 1
BurpBountyExtension line 174: Index 1 out of bounds for length 1
BurpBountyExtension line 174: Index 1 out of bounds for length 1
BurpBountyExtension line 174: Index 1 out of bounds for length 1
BurpBountyExtension line 174: Index 1 out of bounds for length 1
BurpBountyExtension line 174: Index 1 out of bounds for length 1
BurpBountyExtension line 174: Index 1 out of bounds for length 1
BurpBountyExtension line 174: Index 1 out of bounds for length 1
BurpBountyExtension line 174: Index 1 out of bounds for length 1
BurpBountyExtension line 174: Index 1 out of bounds for length 1
BurpBountyExtension line 174: Index 1 out of bounds for length 1
BurpBountyExtension line 174: Index 1 out of bounds for length 1
BurpBountyExtension line 174: Index 1 out of bounds for length 1
BurpBountyExtension line 174: Index 1 out of bounds for length 1
BurpBountyExtension line 174: Index 1 out of bounds for length 1
BurpBountyExtension line 174: Index 1 out of bounds for length 1
BurpBountyExtension line 174: Index 1 out of bounds for length 1
BurpBountyExtension line 174: Index 1 out of bounds for length 1
BurpBountyExtension line 174: Index 1 out of bounds for length 1
BurpBountyExtension line 174: Index 1 out of bounds for length 1
BurpBountyExtension line 174: Index 1 out of bounds for length 1
BurpBountyExtension line 174: Index 1 out of bounds for length 1
BurpBountyExtension line 174: Index 1 out of bounds for length 1
BurpBountyExtension line 174: Index 1 out of bounds for length 1
BurpBountyExtension line 174: Index 1 out of bounds for length 1
BurpBountyExtension line 174: Index 1 out of bounds for length 1
BurpBountyExtension line 174: Index 1 out of bounds for length 1
BurpBountyExtension line 174: Index 1 out of bounds for length 1
BurpBountyExtension line 174: Index 1 out of bounds for length 1
BurpBountyExtension line 174: Index 1 out of bounds for length 1
BurpBountyExtension line 174: Index 1 out of bounds for length 1
BurpBountyExtension line 174: Index 1 out of bounds for length 1
BurpBountyExtension line 174: Index 1 out of bounds for length 1
BurpBountyExtension line 174: Index 1 out of bounds for length 1
BurpBountyExtension line 174: Index 1 out of bounds for length 1
BurpBountyExtension line 174: Index 1 out of bounds for length 1
BurpBountyExtension line 174: Index 1 out of bounds for length 1
BurpBountyExtension line 174: Index 1 out of bounds for length 1
BurpBountyExtension line 174: Index 1 out of bounds for length 1
BurpBountyExtension line 174: Index 1 out of bounds for length 1
BurpBountyExtension line 174: Index 1 out of bounds for length 1
BurpBountyExtension line 174: Index 1 out of bounds for length 1
BurpBountyExtension line 174: Index 1 out of bounds for length 1
BurpBountyExtension line 174: Index 1 out of bounds for length 1
BurpBountyExtension line 174: Index 1 out of bounds for length 1
BurpBountyExtension line 174: Index 1 out of bounds for length 1
BurpBountyExtension line 174: Index 1 out of bounds for length 1
BurpBountyExtension line 174: Index 1 out of bounds for length 1
BurpBountyExtension line 174: Index 1 out of bounds for length 1
BurpBountyExtension line 174: Index 1 out of bounds for length 1
BurpBountyExtension line 174: Index 1 out of bounds for length 1
BurpBountyExtension line 174: Index 1 out of bounds for length 1
BurpBountyExtension line 174: Index 1 out of bounds for length 1
BurpBountyExtension line 174: Index 1 out of bounds for length 1
BurpBountyExtension line 174: Index 1 out of bounds for length 1
BurpBountyExtension line 174: Index 1 out of bounds for length 1
BurpBountyExtension line 174: Index 1 out of bounds for length 1
BurpBountyExtension line 174: Index 1 out of bounds for length 1
BurpBountyExtension line 174: Index 1 out of bounds for length 1
BurpBountyExtension line 174: Index 1 out of bounds for length 1
BurpBountyExtension line 174: Index 1 out of bounds for length 1
BurpBountyExtension line 174: Index 1 out of bounds for length 1
BurpBountyExtension line 174: Index 1 out of bounds for length 1
BurpBountyExtension line 174: Index 1 out of bounds for length 1
BurpBountyExtension line 174: Index 1 out of bounds for length 1
BurpBountyExtension line 174: Index 1 out of bounds for length 1
BurpBountyExtension line 174: Index 1 out of bounds for length 1
```
full errors .

**Comment by s1xg0d** [comment]
> Hi @s1xg0d !
> 
> Can you show me the error from the beginning?
> 
> Thanks!

I reloaded the plugin and scanned it, and this error kept coming up.
`BurpBountyExtension line 174: Index 1 out of bounds for length 1`

**Comment by wagiro** [comment]
Hi @s1xg0d !

Can you try the new jar of the github?

Thanks!
